#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH
GRAPHITE_PATH=/opt/graphite

PYTHONPATH=${GRAPHITE_PATH}/webapp/ django-admin.py syncdb --noinput --settings=graphite.settings

chown -R apache.apache ${GRAPHITE_PATH}/storage
chown -R apache.apache ${GRAPHITE_PATH}/webapp
